# DATA-445: Homework Assignment 2

## Instructions

- This homework assignment is worth **64** points.
- Please submit a **.ipynb** file to Blackboard.
- **Please strive for clarity and organization.**
- **AI usage**:
  - AI use is strictly **prohibited** for conceptual exercises.
  - For applied (Python) exercises, you may use AI exclusively for **debugging**. Do not use AI to generate answers.
- **Due Date: September 18, 2026, by 11:59 PM.**

## Exercise 1

(4 points) Given 1000 records in a dataset, 1000 models are trained with 999 records as part of the training sample and the remaining 1 sample for testing, and the error rate is averaged out, this validation technique is called

(a) validation set  
(b) $k$-fold cross validation  
(c) LOOCV  
(d) Bootstrapping  
(e) None of the above

The answer is (c) LOOCV or Leave one out cross validation

## Exercise 2

(4 points) In $k$-fold cross validation technique, the value of $k$ being small could lead to which of the following in relation to the error rate

(a) low bias and low variance  
(b) low bias and high variance  
(c) high bias and low variance  
(d) high bias and high variance  
(e) All of the above

The answer is (c). The smaller the value of k in the k-fold the high the bias and lower the variance.

## Exercise 3

(4 points) In $k$-fold cross validation technique, the value of $k$ being large could lead to which of the following in relation to the error rate

(a) low bias and low variance  
(b) low bias and high variance  
(c) high bias and low variance  
(d) high bias and high variance  
(e) All of the above

The answer is (b). The larger the k in the k-fold the lower the bias but the higher the vairance.

## Exercise 4

(6 points) Explain what regularization is and why it is useful.

Regularization is like stopping your model from trying too hard to fit the training data. It helps to penalize the model and stop it from becoming too complicated. The main goal is to minimize large coefficients and reduce overfitting so the model can work well with new data, not just the training data.

## Exercise 5

(4 points) Suppose you perform 10-fold cross validation on a dataset with 500 observations. How many observations are used to **train** each of the 10 models?

(a) 50  
(b) 450  
(c) 500  
(d) 5  
(e) None of the above

The answer is (a) 50 observations. 50*10 = 500.

## Exercise 6

(6 points) Explain the difference between the validation set approach and $k$-fold cross validation, and describe one advantage of using $k$-fold cross validation over the validation set approach.

Using the 500 observations example from above. Validation set would be like choosing an 80/20 split or 400 observations as the training data and 100 as the testing data. The downside to this is that the results are all dependent on the 100 observations you use to test on. In the k-fold, using the same 500 observations and 10 groups, you get 10 groups of 50 observations. 1 group is used as the testing data and 9 are the training. When on group has been tested they rotate out and go to training data for a new group to step up as the testing and so on through all the groups. k-folds advantage over validation set approach is that since it tests on several subsets of the data that it's results are more reliable.

## Exercise 7

Consider the `framingham.csv` data file. The dataset is publically available on the Kaggle website, and it is from an ongoing cardiovascular study on residents of the town of Framingham, Massachusetts. The classification goal is to predict whether the patient has 10-year risk of future coronary heart disease (CHD). The dataset provides the patients' information. It includes over 4,000 records and 15 attributes. Each attribute is a potential risk factor. There are both demographic, behavioral and medical risk factors.

- Demographic:
  - Sex: male or female (Nominal)
  - Age: Age of the patient; (Continuous - Although the recorded ages have been truncated to whole numbers, the concept of age is continuous)

- Behavioral:
  - Current Smoker: whether or not the patient is a current smoker (Nominal)
  - Cigs Per Day: the number of cigarettes that the person smoked on average in one day. (can be considered continuous as one can have any number of cigarettes, even half a cigarette.)

- Medical (history):
  - BP Meds: whether or not the patient was on blood pressure medication (Nominal)
  - Prevalent Stroke: whether or not the patient had previously had a stroke (Nominal)
  - Prevalent Hyp: whether or not the patient was hypertensive (Nominal)
  - Diabetes: whether or not the patient had diabetes (Nominal)

- Medical (current):
  - Tot Chol: total cholesterol level (Continuous)
  - Sys BP: systolic blood pressure (Continuous)
  - Dia BP: diastolic blood pressure (Continuous)
  - BMI: Body Mass Index (Continuous)
  - Heart Rate: heart rate (Continuous - In medical research, variables such as heart rate though in fact discrete, yet are considered continuous because of large number of possible values.)
  - Glucose: glucose level (Continuous)

- Predict variable (desired target):
  - 10 year risk of coronary heart disease CHD (binary: "1", means "Yes", "0" means "No")

In **Python**, answer the following:

**(a)** (4 points) Using the pandas library, read the csv data file and create a data-frame called `heart`.

In [2]:
# Your code here
import pandas as pd
import seaborn as sns
# import numpy as np
import matplotlib.pyplot as plt
# from sklearn.linear_model import Lasso (or Ridge or ElasticNet)
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

heart = pd.read_csv('framingham.csv')
heart.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

**(b)** (3 points) Remove observations with missing values.

In [3]:
# Your code here
heart.dropna()
heart.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

**(c)** (25 points) Perform a 5-folds cross validation with the goal of measuring the performance, in terms of F1-score, of two competing models:

- Using `age`, `currentSmoker`, `totChol`, `sysBP`, `diaBP`, `BMI`, `heartRate`, and `glucose` as the predictor variables, and `TenYearCHD` as the target variable build a logistic regression model under the 5-folds cross validation framework. Compute and store the F1-score for each iteration.
- Using `age`, `currentSmoker`, `totChol`, `BMI`, `heartRate`, and `glucose` as the predictor variables, and `TenYearCHD` as the target variable build a logistic regression model under the 5-folds cross validation framework. Compute and store the F1-score for each iteration.

Use 25% as threshold to change the likelihoods to labels. Make sure to scale the input variables of both models to 0-1 range (see [`MinMaxScaler`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html)) before you run the 5-fold cross validation framework. Also, you can use the [`f1_score`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html) function to compute the F1-score.

In [19]:
# Your code here
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import f1_score

scaler = MinMaxScaler()
heart = heart.dropna()

X = heart[['age', 'currentSmoker', 'totChol', 'sysBP', 'diaBP', 'BMI', 'heartRate', 'glucose']]
X2 = heart[['age', 'currentSmoker', 'totChol', 'BMI', 'heartRate', 'glucose']]
Y = heart['TenYearCHD']

X_scaled = scaler.fit_transform(X)
X2_scaled = scaler.fit_transform(X2)

k = KFold(n_splits=5, shuffle=True, random_state=42)

X_model = []
X2_model = []

for train_index, test_index in k.split(X_scaled):
    
    X_train = X_scaled[train_index]
    X_test = X_scaled[test_index]
    
    Y_train = Y.iloc[train_index]
    Y_test = Y.iloc[test_index]
    model = LogisticRegression()
    model.fit(X_train, Y_train)
    
    probability = model.predict_proba(X_test)[:, 1]
    
    Y_pred = (probability >= 0.25).astype(int)
    
    f1 = f1_score(Y_test, Y_pred)
    
    X_model.append(f1)

print("F1 scores for model with all features:", [round(score, 3) for score in X_model])

for train_index, test_index in k.split(X2_scaled):
    
    X_train = X2_scaled[train_index]
    X_test = X2_scaled[test_index]
    
    Y_train = Y.iloc[train_index]
    Y_test = Y.iloc[test_index]
    model = LogisticRegression()
    model.fit(X_train, Y_train)
    
    probability2 = model.predict_proba(X_test)[:, 1]
    
    predictions = (probability2 >= 0.25).astype(int)
    
    score = f1_score(Y_test, predictions)
    
    X2_model.append(score)

print("F1 scores for model without sysBP and diaBP:", [round(score, 3) for score in X2_model])

F1 scores for model with all features: [0.348, 0.351, 0.288, 0.406, 0.309]
F1 scores for model without sysBP and diaBP: [0.288, 0.293, 0.332, 0.392, 0.314]

**(d)** (4 points) Report the average F1-score of each of the models. What model would you use to predict `TenYearCHD`? Explain.

In [20]:
# Your code here
print("Average F1 Model 1:", round(sum(X_model) / len(X_model), 3))
print("Average F1 Model 2:", round(sum(X2_model) / len(X2_model), 3))

Average F1 Model 1: 0.34
Average F1 Model 2: 0.324

I would use F1 model 1 because it preformed better when the 'sysBP' and 'diaBP' were included.